### ISSUE TITLE
Add Generic chart for AWS Web service

### ISSUE THREAD

**Issue by arvegadev** [prefapp/charts#2]
### Motivation

We would like to have a generic chart that exposes a service through ALB and uses the parameter store (optional).

We use to have a deployment, an ingress and a service.

```yaml {{- define "srec-sinvadstt.deployment.data" -}}
#deployment.yaml
name: {{ .Release.Name }}
selector: {{ .Values.selector | toYaml | nindent 2 }}

containers_dict:
  app:
    name: app
    image: {{ .Values.sinvadstt.image }}
    ports: {{ .Values.ports | toYaml | nindent 6 }}

{{- end -}}

{{ include "ph.deployment.render"  (include "srec-sinvadstt.deployment.data" . | fromYaml )}}
```

```yaml 
#ingress.yaml
{{- define "srec-sinvadstt.ingress.data" -}}

version: 1.21.5
name: {{.Release.Name }}
annotations: 
  kubernetes.io/ingress.class: alb
{{ with .Values.ingressAnnotations }}
{{ . | toYaml | nindent 2 }}
{{ end }}
rules_path:
- path: /
  service: {{ .Release.Name }}
  port: 80

host: {{ .Values.host }}

{{- end -}}

{{ include "ph.ingress.render" (include "srec-sinvadstt.ingress.data" . | fromYaml) }}

```

```yaml
#service.yaml
{{- define "srec-sinvadstt.service.data" -}}

name: {{.Release.Name }}

selector: {{.Values.selector | toYaml | nindent 2 }}

ports: {{ .Values.ports | toYaml | nindent 6 }}


{{- end -}}

{{ include "ph.service.render" (include "srec-sinvadstt.service.data" . | fromYaml) }}

```

### Acceptance criteria

- To work with the ALB annotations, we must have deployed [the official ALB Chart](https://artifacthub.io/packages/helm/aws/aws-load-balancer-controller)
