### ISSUE TITLE
Use Role and RoleBindings instead of cluster-wide relatives

### ISSUE THREAD

**Issue by alambike** [prefapp/charts#306]
### Motivation
In the [argo-workflows-operations chart](https://github.com/prefapp/charts/tree/master/charts/argo-workflows-operations) we are making use of ClusterRole and ClusterRoleBindings even these cluster-wide resources are not needed by the deployment.

We want to replace these cluster-wide resources by its equivalent namespace resources: Role & Role-binding

Also, we may need to render a SecretStore and an ExternalSecret, per helm release, leveraging the `releaseName`:

- New helm values needed:
```yaml
global:
  ...
  vault_url: # url for the Vault
  vault_provider: azurekv
  secrets: <to be determined, what params are needed?>
    remote_ref: 
      key:
      template:...
    
```
To render: 

A SecretStore:

```yaml
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secrets-store
  namespace: myns
spec: 
  provider:
    azurekv:
      authType: WorkloadIdentity
      environmentType: PublicCloud
      serviceAccountRef:
        name: my-SA
      vaultUrl: https://my-kv.vault.azure.net/
```

And an ExternalSecret:
```yaml
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-secret
  namespace: myns
spec:
  data:
  - remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      key: myKey
      metadataPolicy: None
    secretKey: my-secret-key
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: my-secrets-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: integrations-secrets
    template:
      data:
        integration1_id: "812906"
        integration2_key: '{{ .myKey }}'
      engineVersion: v2
      mergePolicy: Replace
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
```

### Acceptance criteria
- [ ] New `argo-worklflows-operations` chart version without cluster-wide resources
