### ISSUE TITLE
Maintenance mode is not working propertly when you activate it to true 

### ISSUE THREAD

**Issue by arvegadev** [prefapp/charts#54]
# Expected Behavior

If you activate  ```maintenance_mode``` , the ```deployment.command``` should not run.

# Current Behavior

What is the current behavior?

![image](https://user-images.githubusercontent.com/91343444/170242998-8072779f-d45f-4c60-89d0-46cabb703517.png)

## Steps to Reproduce

In yout values, set ```maintenance_mode: true``` and then add a command in ```deployment.command```:

```yaml 

  maintenance_mode: true
  deployment:
  app: consumidoretl
  containerPort: 8080
  replicas: 1
  command:
    - java -jar /cofrico_datamartetl.jar
    - --mysql_url=${mysql_url}
    - --mysql_user=${mysql_user}
    - --mysql_pass=${mysql_pass}
    - --timescaledb_url=${timescaledb_url}
    - --timescaledb_user=${timescaledb_user}
    - --timescaledb_pass=${timescaledb_pass}
    - --rabbit_addresses=${rabbit_addresses}
    - --mail_uno=${mail_uno}
    - --mail_user=${mail_user}
    - --mail_pass=${mail_pass}

```
